// Schema of the demo's two data files (steps/*.json, fixtures/*.json — both
// generated by generate_fixtures.py, never hand-edited).
import type { StudioGeneratedFile, StudioGraph, StudioRelease } from '../studioApi'
//
// The contract is the methodology (docs/guides/ai-studio-demo-methodology.md
// §3/§5): a Step is event + state transition + UI feedback, and every Step
// names a fixture holding the COMPLETE replayable state. before/after are
// derived from that fixture at generation time, which is what lets the script
// test assert the transition against the real business DOM rather than
// against a hand-written wish.

/** The state-machine read of one snapshot, the vocabulary every step's
 * before/after speaks (§2's objects: the doc's dirty bit, the three icons,
 * the two record counts). */
export interface DemoState {
  doc: string
  /** buffer differs from the last commit */
  dirty: boolean
  diffIcon: 'gray' | 'active'
  draftRecords: number
  historyIcon: 'gray' | 'list'
  versions: number
  versionsIcon: 'gray' | 'list'
  /** graph vocabulary (ACP-729), present only for worlds whose snapshots
   * carry a graph: the node total, and how many THIS step's story added */
  graphNodes?: number
  graphAddedNodes?: number
  /** release vocabulary (ACP-730), same gate as the graph fields: whether
   * a version has been cut, and how many files it generated */
  released?: boolean
  generatedFiles?: number
}

/** One step's visual-guidance instruction (§4): what to ring, what the hint
 * bar says, and which UI the guidance layer must open on the business page
 * (a locator list, clicked in order after the step mounts and settles). */
export interface DemoHighlight {
  /** key into the demo locator map (locators.ts) — NOT a raw CSS selector,
   * so the script survives a class rename inside the business components */
  target: string
  hint: string
  open: string[]
}

export interface DemoStep {
  id: string
  title: string
  /** branch id ("alt-1"/"alt-2") or null for the main line (§7) */
  branch: string | null
  /** fixtures/state-<fixture>.json to load on ENTERING this step */
  fixture: string
  /** for live-act steps (main-8's commit, main-10's release): the snapshot
   * the step's real business click LANDS on — the workbench resolves it to
   * show the landed state (release panel + code view) without inventing any
   * of it. Absent = the step lands where it entered. */
  afterFix?: string
  /** labels a release step's control walks while its real click lands */
  releasePhases?: string[]
  before: DemoState
  action: { event: string }
  after: DemoState
  highlight: DemoHighlight
  // ---- 验收文档七字段（T10 / ACP-732，出处见 generate_fixtures.py 的
  // TARGET_VIEW 注释）：三件套字段全部保留，以下六项由派生数据拼装；
  // 「页面有什么变化」即上面的 before/after，不重复存 ----
  /** 从哪里开始：进入本步时状态层的可读画面（before 观测的渲染） */
  startFrom: string
  /** 用户做什么：既有事件描述（与 action.event 逐字相同） */
  userAction: string
  /** 去了哪里：本步高亮目标所属的视图名 */
  goesTo: string
  /** 用户看到什么：既有提示文案（与 highlight.hint 逐字相同） */
  userSees: string
  /** 后台发生什么：前后快照观测差的一句话（派生） */
  backendFact: string
  /** 怎样算通过：本步断言清单，由 after 观测逐项生成；预检逐条校验
   * （字段在观测词表内且等于 after 观测），剧本测试逐条消费 */
  passCriteria: { field: string; eq: boolean | number; note: string }[]
}

export interface DemoScript {
  scenario: string
  title: string
  project: string
  steps: DemoStep[]
}

/** One snapshot: the fake backend's whole in-memory world for one step —
 * shaped exactly like the four studioApi responses the workbench reads. */
export interface DemoFixture {
  project: { id: string; name: string; description: string; createdAt: number }
  /** the doc the demo focuses (the editor tab opens on it) */
  focusDoc: string
  /** the editor buffer, which may differ from the committed content — that
   * difference IS the dirty state the snapshot carries */
  buffer: string
  docs: { name: string; content: string }[]
  draftVersions: { name: string; time: number; content: string }[]
  versions: Record<string, { name: string; time: number; diff: string }[]>
  /** the requirement graph the commits feed (ACP-729), as the snapshot froze
   * it. Absent = this world has no graph story, and no graph panel renders. */
  graph?: StudioGraph
  /** which of `graph` this snapshot's STORY added (the commit between this
   * step and its predecessor): node ids, and edges spelled "from->to". The
   * generator cross-checks it against the previous snapshot, so the highlight
   * is a derived fact, not a wish. */
  graphDelta?: { nodes: string[]; edges: string[] }
  /** a cut release (ACP-730), present once the story has pressed 发版 */
  release?: StudioRelease
  /** the code the release generated from the graph; each file names its
   * requirement nodes, and the generator proved every one of them is part of
   * `generatedFrom`'s graph delta. */
  generatedFiles?: StudioGeneratedFile[]
  /** audit anchor: which snapshot's graphDelta `generatedFiles` trace to */
  generatedFrom?: string
}
