// Schema of the demo's two data files (steps/*.json, fixtures/*.json — both
// generated by generate_fixtures.py, never hand-edited).
//
// The contract is the methodology (docs/guides/ai-studio-demo-methodology.md
// §3/§5): a Step is event + state transition + UI feedback, and every Step
// names a fixture holding the COMPLETE replayable state. before/after are
// derived from that fixture at generation time, which is what lets the script
// test assert the transition against the real business DOM rather than
// against a hand-written wish.

/** The state-machine read of one snapshot, the vocabulary every step's
 * before/after speaks (§2's objects: the doc's dirty bit, the three icons,
 * the two record counts). */
export interface DemoState {
  doc: string
  /** buffer differs from the last commit */
  dirty: boolean
  diffIcon: 'gray' | 'active'
  draftRecords: number
  historyIcon: 'gray' | 'list'
  versions: number
  versionsIcon: 'gray' | 'list'
}

/** One step's visual-guidance instruction (§4): what to ring, what the hint
 * bar says, and which UI the guidance layer must open on the business page
 * (a locator list, clicked in order after the step mounts and settles). */
export interface DemoHighlight {
  /** key into the demo locator map (locators.ts) — NOT a raw CSS selector,
   * so the script survives a class rename inside the business components */
  target: string
  hint: string
  open: string[]
}

export interface DemoStep {
  id: string
  title: string
  /** branch id ("alt-1"/"alt-2") or null for the main line (§7) */
  branch: string | null
  /** fixtures/state-<fixture>.json to load on ENTERING this step */
  fixture: string
  before: DemoState
  action: { event: string }
  after: DemoState
  highlight: DemoHighlight
}

export interface DemoScript {
  scenario: string
  title: string
  project: string
  steps: DemoStep[]
}

/** One snapshot: the fake backend's whole in-memory world for one step —
 * shaped exactly like the four studioApi responses the workbench reads. */
export interface DemoFixture {
  project: { id: string; name: string; description: string; createdAt: number }
  /** the doc the demo focuses (the editor tab opens on it) */
  focusDoc: string
  /** the editor buffer, which may differ from the committed content — that
   * difference IS the dirty state the snapshot carries */
  buffer: string
  docs: { name: string; content: string }[]
  draftVersions: { name: string; time: number; content: string }[]
  versions: Record<string, { name: string; time: number; diff: string }[]>
}
